### Numpy Library
- Numpy stands for numerical python
- This library has a lot of numerical operations that help do complex operations at a high speed.
- Numpy is the back end of many other libraries (pandas, matplotlib)
- There is only one type of data abstraction (data type) in numpy - numpy nd array - numpy n-dimensional array

In [ ]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)
#Numpy version greater than 2.0 are unstable. There are compatability issues with other functions

1.26.4

!pip uninstall numpy -y
!pip install numpy<2 --no-cache-dir
!pip install numpy=1.26      #1.21, 1.16
!pip install --force-reinstall numpy==1.20   #Force reinstall a specific version

In [5]:
arr1 = np.array(10)    #Creating a numpy array from a scalar number
arr2 = np.array([1,2,3,4,5,7])    #Creating a numpy array from a list. You can create from a tuple also
arr3 = np.array([[1,2,3],[4,5,6],[2,3,4],[12,13,14]])  #Creating numpy array from a nested list.

#### Attributes of numpy array
- type(arr) - Will tell you the datatype of the variable as a whole
- arr.shape - Will tell you the number of rows and columns (it hels us to understand the structure of the array)
- arr.ndim - Will tell you how many dimensions of array the data is
- arr.dtype - Will tell you the datatype of elements inside it
- arr.size - Will tell you the total number of elements inside the array

In [7]:
print(arr1, type(arr1), arr1.shape, arr1.ndim, arr1.dtype, arr1.size)

10 <class 'numpy.ndarray'> () 0 int32 1

In [8]:
print(arr2, type(arr2), arr2.shape, arr2.ndim, arr2.dtype, arr2.size)

[1 2 3 4 5 7] <class 'numpy.ndarray'> (6,) 1 int32 6

In [9]:
print(arr3, type(arr3), arr3.shape, arr3.ndim, arr3.dtype, arr3.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 2  3  4]
 [12 13 14]] <class 'numpy.ndarray'> (4, 3) 2 int32 12

In [10]:
#Numpy arrays expect symmetry, they are designed to be homogenous
a = [[1,2,3],[4,5],[6]]
print(a)

[[1, 2, 3], [4, 5], [6]]

In [12]:
#np.array(a)   #Will throw an error because numpy arrays have to be symmetric by default

In [13]:
a = [[1,2,3],[4,5,'a'],[7,8,True]]
arr3 = np.array(a)

In [36]:
print(arr3, type(arr3), arr3.shape, arr3.ndim, arr3.dtype, arr3.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 2  3  4]
 [12 13 14]] <class 'numpy.ndarray'> (4, 3) 2 int32 12

### Homework
- Create a numpy array from a set and dictionary and tell me your observations.

In [3]:
a = np.array({2,3})
print(a, type(a), a.dtype)

{2, 3} <class 'numpy.ndarray'> object

In [10]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])

In [11]:
#Reshape function
print(arr2)
arr4 = arr2.reshape(3,3)
print()
print(arr4)
print()
print(arr2)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]

In [37]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 2,  3,  4],
       [12, 13, 14]])

In [38]:
arr3.reshape( 6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 2,  3],
       [ 4, 12],
       [13, 14]])

In [39]:
arr3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  2,  3,  4, 12, 13, 14])

In [40]:
#arr2.reshape(4,7)  #Throws an error because elements are insufficient

In [41]:
#Built in array generators - arange, zeros, ones, linspace, eye, rand, randn, randint
np.arange(1,7,2)   #Generates values from start to stop in steps of 1 (or step specified)

array([1, 3, 5])

In [42]:
#np.zeros(5)    #Generates a matrix filled of 0s
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [43]:
#np.ones(6)   #Generats a matrix filled of 1s
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
np.linspace(0,100,5) #End point is inclusive by default. Generates a linear array of equally spaced count(default 50) of numbers between start and stop value

array([  0.,  25.,  50.,  75., 100.])

In [45]:
np.linspace(3,10).reshape(2,5,5)     #To reshape the output into a multi dimensional array

array([[[ 3.        ,  3.14285714,  3.28571429,  3.42857143,
          3.57142857],
        [ 3.71428571,  3.85714286,  4.        ,  4.14285714,
          4.28571429],
        [ 4.42857143,  4.57142857,  4.71428571,  4.85714286,
          5.        ],
        [ 5.14285714,  5.28571429,  5.42857143,  5.57142857,
          5.71428571],
        [ 5.85714286,  6.        ,  6.14285714,  6.28571429,
          6.42857143]],

       [[ 6.57142857,  6.71428571,  6.85714286,  7.        ,
          7.14285714],
        [ 7.28571429,  7.42857143,  7.57142857,  7.71428571,
          7.85714286],
        [ 8.        ,  8.14285714,  8.28571429,  8.42857143,
          8.57142857],
        [ 8.71428571,  8.85714286,  9.        ,  9.14285714,
          9.28571429],
        [ 9.42857143,  9.57142857,  9.71428571,  9.85714286,
         10.        ]]])

In [46]:
np.eye(5)    #Generates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
#rand, randn, randint
np.random.rand(4,5)   #Random float values between 0 and 1 (1 is exclusive) in the shape specified

array([[0.65220082, 0.04309188, 0.18883419, 0.5502531 , 0.36713175],
       [0.05744801, 0.03415586, 0.86167342, 0.00526648, 0.77558018],
       [0.9483551 , 0.4365542 , 0.00650444, 0.34951978, 0.8633586 ],
       [0.74020613, 0.95918082, 0.79231725, 0.36830644, 0.61918809]])

In [57]:
demo = np.random.randn(1000)   #Random float values that belong to a SND (Standard normla distribution)

In [58]:
demo.mean()

0.005692008253209275

In [59]:
demo.std()

1.0079104214360097

In [62]:
np.random.randint(3,7,12)   #Generates specified count (default 1) of values randomly picked between start value and stop value

array([3, 3, 3, 3, 3, 6, 3, 3, 5, 4, 3, 6])

In [ ]:
#Broadcasting in numpy
a = np.array([[2,3,4],[4,5,6],[6,7,8]])
b = np.array([5,6,7])

In [78]:
#Aggregations on numpy arrays
a = np.array([2,3,4,5,7,3,1,3,100,7,9,0,6,12,3,4,6,8,9])

In [79]:
np.min(a)   #MInimum value in the array

0

In [80]:
np.max(a)   #Maximum value in the array

100

In [81]:
np.argmin(a)    #Index position of the minimum value

11

In [82]:
np.argmax(a)     #Index position of the maximum value

8

In [83]:
np.mean(a)  #Mean value

10.105263157894736

In [84]:
np.median(a)   #Median

5.0

In [85]:
#np.where
#Task: Filter those elements which are even
np.where(a%2==0)   #Gives the indices of elements that satisfy the condition

(array([ 0,  2,  8, 11, 12, 13, 15, 16, 17], dtype=int64),)

In [86]:
a[np.where(a%2==0)]

array([  2,   4, 100,   0,   6,  12,   4,   6,   8])

In [ ]:
#Task: Filter those elements which are greater than 5
a[np.where(a>5)]

In [87]:
#Indexing and Slicing
print(a)
print(a[2:7])

[  2   3   4   5   7   3   1   3 100   7   9   0   6  12   3   4   6   8
   9]
[4 5 7 3 1]

In [ ]:
a = np.random.randint(2,20,30).reshape(2,3,5)
a

In [ ]:
a[0,1:3,2:5]

### Pandas is a library that helps you handle tabular data
- Data in Pandas is stored as dataframes, a 2-d structure similar to the tables in excel
- Pandas offers transformations, data cleaning, preprocessing options, and hence pandas library becomes an eminent part of life of DE and DS
- Pandas offers two data abstraction models - Series and DataFrame

In [ ]:
#Series in pandas is a 1-d data. Dataframe is a 2-d data. Other than that we do not have any dimensional data in pandas

In [88]:
import pandas as pd
#A series can be constructed from a list, tuple, a np.1-d array, a dictionary. But a series cannot be constructed from a set.
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [89]:
ser1 = pd.Series((3,4,5,6),index=['row1','row2','row3','row4'],name='Series1')
ser1

row1    3
row2    4
row3    5
row4    6
Name: Series1, dtype: int64

Task: Create a pandas series with dictionary, a numpy array and a set. Observe how it is created

In [90]:
df = pd.DataFrame([[1,2,3,4,5],[5,6,7]])
df

   0  1  2    3    4
0  1  2  3  4.0  5.0
1  5  6  7  NaN  NaN

In [91]:
df2=pd.DataFrame(ser1)
df2

      Series1
row1        3
row2        4
row3        5
row4        6

In [93]:
df = pd.DataFrame([[1,2,3],[6,7,8],[9,4,3,2,6,8]], index=['row1','row2','row3'], columns = ['col1','col2','col3','col4','col5','col6'])
df

      col1  col2  col3  col4  col5  col6
row1     1     2     3   NaN   NaN   NaN
row2     6     7     8   NaN   NaN   NaN
row3     9     4     3   2.0   6.0   8.0

In [94]:
df.rename(columns = {'col1':'c1'}, inplace=True)   #inplace=True ensures that a permanent change is done in the variable

In [95]:
df

      c1  col2  col3  col4  col5  col6
row1   1     2     3   NaN   NaN   NaN
row2   6     7     8   NaN   NaN   NaN
row3   9     4     3   2.0   6.0   8.0

In [97]:
#Indexing a value or a row or a column
#df[0] #Throws an error because there is no column with name as 0
df[0]   #Each column in a dataframe acts like a series

KeyError: 0

In [98]:
df[['c1','col4']]

      c1  col4
row1   1   NaN
row2   6   NaN
row3   9   2.0

In [100]:
df['c1'][2]    #df['c1'][2] also works. For rows we can use their index also. For columns col name is compulsory

C:\Users\Datamites\AppData\Local\Temp\ipykernel_16612\8647863.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['c1'][2]    #df['c1'][2] also works. For rows we can use their index also. For columns col name is compulsory

9

In [101]:
df['c1'][2]

C:\Users\Datamites\AppData\Local\Temp\ipykernel_16612\2249024773.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['c1'][2]

9

In [102]:
df['col7'] =  'a'
df

      c1  col2  col3  col4  col5  col6 col7
row1   1     2     3   NaN   NaN   NaN    a
row2   6     7     8   NaN   NaN   NaN    a
row3   9     4     3   2.0   6.0   8.0    a

In [103]:
df['col8'] = [5.2,6.7,8.9]
df

      c1  col2  col3  col4  col5  col6 col7  col8
row1   1     2     3   NaN   NaN   NaN    a   5.2
row2   6     7     8   NaN   NaN   NaN    a   6.7
row3   9     4     3   2.0   6.0   8.0    a   8.9

In [171]:
#File reading in pandas
#read_csv is command to read csv files, read_excel is to read excel sheets
df = pd.read_csv(r'D:\Rahul\Downloads\titanic.csv')
#df = pd.read_csv('train.csv')   #This works if the file is in same folder as jupyter notebook

In [105]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [109]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [110]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [111]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [112]:
df.describe(include='O')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [113]:
df.shape

(891, 12)

In [114]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [115]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [116]:
type(df)

pandas.core.frame.DataFrame

In [117]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [118]:
df.Sex.unique()

array(['male', 'female'], dtype=object)

In [119]:
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [120]:
#Locate a value in the database
df.Sex[3]
df['Sex'][3]

'female'

### Locaters and Ilocaters
#### Locaters are name based access of rows and columns. If rows are not named, row numbers also work
- df.loc[col_name,row_name]
- df.loc[[list of col names],[list of row names]]
- df.loc[[list of col_ names] start_row:end_row]
#### Ilocaters are index based access of rows and columns. 
- df.iloc[col_index,row_name]
- df.iloc[[list of col names],[list of row names]]
- df.iloc[start_col:end_col, start_row:end_row]

In [121]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [124]:
df.loc[4,'Age']

35.0

In [126]:
df.loc[4,:]   #df.loc[493] also retrieves the same row.

PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object

In [128]:
df.loc[4, ['Embarked','Name','Survived']]

Embarked                           S
Name        Allen, Mr. William Henry
Survived                           0
Name: 4, dtype: object

In [129]:
df.loc[4:15,['Embarked','Name','SibSp']]

   Embarked                                               Name  SibSp
4         S                           Allen, Mr. William Henry      0
5         Q                                   Moran, Mr. James      0
6         S                            McCarthy, Mr. Timothy J      0
7         S                     Palsson, Master. Gosta Leonard      3
8         S  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      0
9         C                Nasser, Mrs. Nicholas (Adele Achem)      1
10        S                    Sandstrom, Miss. Marguerite Rut      1
11        S                           Bonnell, Miss. Elizabeth      0
12        S                     Saundercock, Mr. William Henry      0
13        S                        Andersson, Mr. Anders Johan      1
14        S               Vestrom, Miss. Hulda Amanda Adolfina      0
15        S                   Hewlett, Mrs. (Mary D Kingcome)       0

In [130]:
df.loc[[790,34,800,1],['Name','Embarked']]

                                                  Name Embarked
790                           Keane, Mr. Andrew "Andy"        Q
34                             Meyer, Mr. Edgar Joseph        C
800                               Ponesell, Mr. Martin        S
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        C

In [131]:
df.iloc[[790,34,1],[3,6]]

                                                  Name  SibSp
790                           Keane, Mr. Andrew "Andy"      0
34                             Meyer, Mr. Edgar Joseph      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...      1

In [133]:
#Filtering dataframe based on conditions
#Find all the passenger aged over 70 and their survival status
df.loc[df.Age>70,['Name','Survived','Age']]

                                     Name  Survived   Age
96              Goldschmidt, Mr. George B         0  71.0
116                  Connors, Mr. Patrick         0  70.5
493               Artagaveytia, Mr. Ramon         0  71.0
630  Barkworth, Mr. Algernon Henry Wilson         1  80.0
851                   Svensson, Mr. Johan         0  74.0

In [ ]:
df

In [138]:
#Find all female passengers traveling alone
df.loc[(df.Sex=='female')&(df.SibSp==0)&(df.Parch==0),['Name','Age']]

                                                  Name   Age
2                               Heikkinen, Miss. Laina  26.0
11                            Bonnell, Miss. Elizabeth  58.0
14                Vestrom, Miss. Hulda Amanda Adolfina  14.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
19                             Masselmani, Mrs. Fatima   NaN
..                                                 ...   ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0
865                           Bystrom, Mrs. (Karolina)  42.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
882                       Dahlberg, Miss. Gerda Ulrika  22.0
887                       Graham, Miss. Margaret Edith  19.0

[126 rows x 2 columns]

- Get all names of passengers who boarded at 'Q'
- Get the details of passengers who are traveling alone
- Get the name and survival status of passengers who are traveling alone.
- Get the name and age of female passengers who traveled in 3rd class.

In [140]:
# pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
# pd.reset_option('display.max_rows',None)
# pd.reset_option('display.max_columns',None)

In [143]:
#Aggregations on the database - groupby
df.groupby("Sex").describe()

       PassengerId                                                             \
             count        mean         std  min     25%    50%     75%    max
Sex
female       314.0  431.028662  256.846324  2.0  231.75  414.5  641.25  889.0
male         577.0  454.147314  257.486139  1.0  222.00  464.0  680.00  891.0

       Survived                                              Pclass            \
          count      mean       std  min  25%  50%  75%  max  count      mean
Sex
female    314.0  0.742038  0.438211  0.0  0.0  1.0  1.0  1.0  314.0  2.159236
male      577.0  0.188908  0.391775  0.0  0.0  0.0  0.0  1.0  577.0  2.389948

                                            Age                              \
            std  min  25%  50%  75%  max  count       mean        std   min
Sex
female  0.85729  1.0  1.0  2.0  3.0  3.0  261.0  27.915709  14.110146  0.75
male    0.81358  1.0  2.0  3.0  3.0  3.0  453.0  30.726645  14.678201  0.42

                                SibSp                                          \
         25%   50%   75%   max  count      mean       std  min  25%  50%  75%
Sex
female  18.0  27.0  37.0  63.0  314.0  0.694268  1.156520  0.0  0.0  0.0  1.0
male    21.0  29.0  39.0  80.0  577.0  0.429809  1.061811  0.0  0.0  0.0  0.0

             Parch                                                Fare  \
        max  count      mean       std  min  25%  50%  75%  max  count
Sex
female  8.0  314.0  0.649682  1.022846  0.0  0.0  0.0  1.0  6.0  314.0
male    8.0  577.0  0.235702  0.612294  0.0  0.0  0.0  0.0  5.0  577.0


             mean        std   min        25%   50%    75%       max
Sex
female  44.479818  57.997698  6.75  12.071875  23.0  55.00  512.3292
male    25.523893  43.138263  0.00   7.895800  10.5  26.55  512.3292

In [142]:
df.groupby('Sex').Age.mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [145]:
#Sorting a dataframe
df.sort_values('Name')
# df.sort_values('Age',ignore_index=True)
#df.sort_values('Age',ignore_index=True,inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,NaN,C
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
286,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NaN,S
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5000,NaN,S
361,362,0,2,"del Carlo, Mr. Sebastiano",male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S

In [146]:
df.Survived.dtype

dtype('int64')

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [148]:
df.Survived = pd.to_numeric(df.Survived,downcast='integer')

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int8
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(4), int8(1), object(5)
memory usage: 77.6+ KB

In [150]:
df.Pclass = df.Pclass.astype('object')

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int8
 2   Pclass       891 non-null    int32
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int32(1), int64(3), int8(1), object(5)
memory usage: 74.1+ KB

In [175]:
# df.Pclass = pd.to_numeric(df.Pclass,downcast='integer') # error = raise , if error ='ignore', error = coerce 
df.Pclass = df.Pclass.astype('int') # you will get an value error

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int32
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int32(1), int64(4), object(5)
memory usage: 80.2+ KB

#### Cleaning the data, Manipulating the data
- Transformations
- De-duplication - Removing the duplicates
- Removing columns
- Imputing values

In [154]:
df.drop_duplicates()  #Eliminate duplicate rows from dataframe
#df.drop_duplicates(inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [159]:
df.dropna()  #Drop those rows with null values

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [160]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [161]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [166]:
df.Age.mean()

29.69911764705882

In [162]:
df.fillna(0)   #Fill a value in the empty cells - Imputing
df.fillna(value={'Sex':'male','Cabin':'Nothing','Embarked':'S'},inplace=True)  #Fill each column's null values with specific values

In [163]:
df.loc[df.Age.isnull(),'Age'] = df.Age.mean()    #Filter the null cells using loc and impute

In [164]:
#Dropping a column
df.drop(['PassengerId','Ticket'],axis=1,inplace=True)

In [165]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,Nothing,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,Nothing,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,Nothing,S
...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,Nothing,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,Nothing,S
889,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Nothing,Q

In [167]:
#Transformations
df['Age_log'] = np.log(df.Age)

In [168]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Age_log
0,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,Nothing,S,3.091042
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C85,C,3.637586
2,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,Nothing,S,3.258097
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,C123,S,3.555348
4,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,Nothing,S,3.555348
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,Nothing,S,3.295837
887,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,B42,S,2.944439
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,Nothing,S,3.391117
889,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C148,C,3.258097
890,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Nothing,Q,3.465736

In [169]:
df['Family'] = df.SibSp + df.Parch

In [170]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Age_log,Family
0,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,Nothing,S,3.091042,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C85,C,3.637586,1
2,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,Nothing,S,3.258097,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,C123,S,3.555348,1
4,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,Nothing,S,3.555348,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,Nothing,S,3.295837,0
887,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,B42,S,2.944439,0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,Nothing,S,3.391117,3
889,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C148,C,3.258097,0
890,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Nothing,Q,3.465736,0